inherit_from: .rubocop_todo.yml

# inherit_from: .rubocop_todo.yml

# Find out more about the rubocop cops  https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml
require:
  # - rubocop-performance
  # - rubocop-rails
  # - rubocop-rspec

AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/**
    - config/*
    - config/initializers/*
    - bin/**/*

Metrics/LineLength:
  Max: 190

Layout/EndOfLine:
  EnforcedStyle: lf

# Check that the first argument to the top level describe is
# the tested class or module.
#   - excluding rake task tests
#
# RSpec/DescribeClass:
#   Exclude:
#     - 'spec/lib/tasks/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
