# Find out more about the rubocop cops  https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml

AllCops:
  Exclude:
    - db/**/*
    - spec/**/*
    - config/**/*
    - bin/**/*

require:
  - rubocop-rails

Layout/LineLength:
  Max: 120

Layout/EndOfLine:
  EnforcedStyle: lf

Naming/MethodParameterName:
  Exclude:
    - app/helpers/email_header_helper.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Rails/Date:
  Enabled: true
