dist: xenial
language: ruby
before_install:
  - gem install bundler --version '= 1.17.1' --no-document
  - bundle _1.17.1_ install
cache: bundler
bundler_args: --without development
rvm:
  - 2.4.2
services:
  - postgresql
before_script:
  - bundle exec rake db:create db:schema:load

script:
  - bundle exec rake
addons:
  code_climate:
    repo_token: 9b6a47d42b4a745a38818eac18dba4ca94ea88f8c7751859ec49b8cedbf010fe
  chrome: stable
notifications:
  email:
    - social@codebar.io
