dist: xenial
language: ruby

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache:
  bundler: true
  directories:
    - vendor/bundle

rvm:
  - 2.4.2

services:
  - postgresql

before_install:
  - gem install bundler --version '~> 1.17.3' --no-document
  - bundle _1.17.3_ install --without development

script:
  - bundle exec rake db:create db:schema:load
  - bundle exec rake

addons:
  code_climate:
    repo_token: 9b6a47d42b4a745a38818eac18dba4ca94ea88f8c7751859ec49b8cedbf010fe
  chrome: stable

notifications:
  email:
    - social@codebar.io
